# Use root/example as user/password credentials
version: "3.1"

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./certificates/ca-crt.pem:/etc/mysql/certificados/ca-crt.pem
            - ./certificates/server-crt.pem:/etc/mysql/certificados/server-crt.pem
            - ./certificates/server-key.pem:/etc/mysql/certificados/server-key.pem
            - ./my.cnf:/etc/my.cnf
        ports:
            - 3306:3306
        # (this is just an example, not intended to be a production configuration)
