version: "3.1"

services:
    db:
        image: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: example
        volumes:
            - ./certificates/ca-crt.pem:/etc/mysql/certificados/ca-crt.pem
            - ./certificates/server-crt.pem:/etc/mysql/certificados/server-crt.pem
            - ./certificates/server-key.pem:/etc/mysql/certificados/server-key.pem
            - ./my.cnf:/etc/my.cnf
        ports:
            - 3306:3306

    db2:
        image: mongo:6.0
        container_name: mongo_ssl
        restart: always
        ports:
            - "27017:27017" # Expose MongoDB on port 27017
        volumes:
            - ./certificados/server.pem:/etc/ssl/mongo/server.pem
            - ./certificados/ca.crt:/etc/ssl/mongo/ca.crt
            - ./certificados/internalClient.pem:/etc/ssl/mongo/internalClient.pem
            - ./certificados/mongod.conf:/etc/mongod.conf
        command: ["mongod", "--config", "/etc/mongod.conf"]
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: password
